[workspace]
resolver = "2"
members = ["core", "cli", "wasm"]

[workspace.package]
version = "0.1.2"
edition = "2024"
license = "ASL2"
authors = ["Anders Christiansen Sørby <anders@sorby.xyz>"]
homepage = "https://monad-lang.org"
repository = "https://tangled.org/monad-lang/monad"

[workspace.dependencies]
nom = "8.0.0"
paste = "1.0"
libc = "0.2"
toml = "0.8"
serde = { version = "1", features = ["derive"] }
