# The self-hosted compiler, as a library.

[mote]
name = "lang"
version = "0.1.2"
edition = "2026"

[lib]
path = "src/lib.mo"

[dependencies.init]
path = "../init"

[dependencies.std]
path = "../std"
